version: '3'
services:
  nginx:
    build: .
    ports:
      - '8443:443'
  keycloak:
    image: 'jboss/keycloak'
    environment:
      - KEYCLOAK_PASSWORD=admin
      - KEYCLOAK_USER=admin
      - DB_VENDOR=h2
      - PROXY_ADDRESS_FORWARDING=true
  microservice:
    image: 'dorbsz/simple-microservice'
    ports:
      - '8888:80'
